---
# Too picky.
Metrics/LineLength:
  Enabled: false

# This should truly be on for well documented gems.
Style/Documentation:
  Enabled: false

# Neatly aligned code is to swell.
Style/SpaceBeforeFirstArg:
  Enabled: false

# Don't mess with RSpec DSL.
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

# Avoid contradictory style rules by enforce single quotes.
Style/StringLiterals:
  EnforcedStyle: single_quotes
